# Generated by Django 4.2.16 on 2024-11-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_profile_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='About',
        ),
    ]
