# Generated by Django 4.2.16 on 2024-11-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='featured_image',
            new_name='profile_image',
        ),
    ]
